name: maki-math-devops

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-build-publish:
    # Only run if PR is NOT from a fork
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: [self-hosted]

    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: |
        dotnet restore
        dotnet tool install --global dotnet-ef --version 10.0.*
    - name: Build
      run: dotnet publish
    - name: Generate Migration Script
      run: |
        export PATH="$PATH:/github/home/.dotnet/tools"
        dotnet ef --project MathAPI migrations script --idempotent --output MathAPI/bin/Release/net10.0/publish/migration.sql
    - name: publish backend
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-artifact
        path: MathAPI/bin/Release/net10.0/publish
        retention-days: 1

  frontend-build-publish:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: ./web-client
    container:
      image: node:22
    steps:
    - uses: actions/checkout@v4
    - name: restore packages
      run: npm install
    - name: build vite
      run: npm run build
    - name: publish frontend
      uses: actions/upload-artifact@v4
      with:
        name: vite-artifact
        path: web-client/dist
        retention-days: 1

  deploy:
     # Only run when code is pushed (merged) to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: [self-hosted]
    needs: ["frontend-build-publish", "backend-build-publish"]
    steps:
      - uses: actions/download-artifact@v5
      - name: stop-backend
        run: ssh maki-math-prod sudo systemctl stop math-api.service
      - name: replace artifacts
        run: |
          rsync -avz --delete $GITHUB_WORKSPACE/vite-artifact/ maki-math-prod:/var/www/math_platform/web-client/dist/
          rsync -avc --delete $GITHUB_WORKSPACE/dotnet-artifact/ maki-math-prod:/var/www/math_platform/publish/
      - name: apply migration
        run: ssh maki-math-prod psql -U math_admin -d math_db -f /var/www/math_platform/publish/migration.sql
      - name: start-backend
        run: ssh maki-math-prod sudo systemctl start math-api.service
